# default_preferences.yml
browser:
  custom_chrome_frame: false
  app_window_placement:
    DevToolsApp:
      always_on_top: false
      bottom: 1049
      left: 1399
      maximized: false
      right: 1919
      top: 20
      work_area_bottom: 1054
      work_area_left: 0
      work_area_right: 1920
      work_area_top: 0
  window_placement:
    bottom: 1054
    left: 0
    maximized: false
    right: 1400
    top: 0
    work_area_bottom: 1054
    work_area_left: 0
    work_area_right: 1920
    work_area_top: 0
devtools:
  preferences:
    currentDockState: "undocked"
  synced_preferences_sync_disabled:
    sidebarPosition: "bottom"
    uiTheme: "light" # dark|light